node_config_path: "/etc/nomad.d/node.hcl"
server_config_path: "/etc/nomad.d/server.hcl"
client_config_path: "/etc/nomad.d/client.hcl"
docker_config_path: "/etc/nomad.d/docker.hcl"
podman_config_path: "/etc/nomad.d/podman.hcl"
