---
- name: Upload Nomad node configuration
  notify: Restart Nomad
  ansible.builtin.template:
    src: node.hcl.j2
    dest: "{{ node_config_path }}"
    owner: "nomad"
    group: "nomad"
    mode: 0644

- name: Configure servers
  notify: Restart Nomad
  block:
    - name: Upload server configuration
      ansible.builtin.template:
        src: server.hcl.j2
        dest: "{{ server_config_path }}"
        owner: "nomad"
        group: "nomad"
        mode: 0644
      when: "'server' in node_role"
    - name: Remove the server configuration if the node is not a server
      ansible.builtin.file:
        path: "{{ server_config_path }}"
        state: absent
      when: "'server' not in node_role"

- name: Configure clients
  notify: Restart Nomad
  block:
    - name: Upload client configuration
      ansible.builtin.template:
        src: client.hcl.j2
        dest: "{{ client_config_path }}"
        owner: "nomad"
        group: "nomad"
        mode: 0644
      when: "'client' in node_role"
    - name: Remove the client configuration if the node is not a client
      ansible.builtin.file:
        path: "{{ client_config_path }}"
        state: absent
      when: "'client' not in node_role"

- name: Configure Docker task driver
  notify: Restart Nomad
  block:
    - name: Configure Docker task driver
      ansible.builtin.include_tasks: "plugins/docker-install.yml"
      when: "'docker' in task_drivers"
    - name: Remove the docker configuration if the plugin has been disabled
      ansible.builtin.include_tasks: "plugins/docker-uninstall.yml"
      when: "'docker' not in task_drivers"

# The podman task driver is available only for linux hosts
- name: Configure Podman task driver
  notify: Restart Nomad
  when: "ansible_system == 'Linux'"
  block:
    - name: Configure Podman task driver
      ansible.builtin.include_tasks: "plugins/podman-install.yml"
      when: "'podman' in task_drivers"
    - name: Remove the podman configuration if the plugin has been disabled
      ansible.builtin.include_tasks: "plugins/podman-uninstall.yml"
      when: "'podman' not in task_drivers"
