---
# The GPG Key and the repository are not removed in order to avoid breaking
# other tools from HashiCorp.
# TODO: Evaluate if makes sense to use a control variable for removing them
#
# - name: Remove HashiCorp GPG Key
#   ansible.builtin.apt_key:
#     url: "{{ apt_key_url }}"
#     state: "{{ state }}"
#
# - name: Make sure HashiCorp Linux repository is present
#   ansible.builtin.apt_repository:
#     repo: "{{ apt_repository }}"
#     state: "{{ state }}"

- name: Install Nomad
  ansible.builtin.apt:
    name: "nomad={{ nomad_version }}-{{ apt_build_number }}"
    state: "{{ state }}"
